name: accept-02
description: "accept go code flowmanager"

supervisor_command: glm52

prompt: |
  if goga binary not installed - install it with `pip install goga && goga connect claude`
  constraint: пиши все на русском. Не используй английский кроме спец терминов нужных.

stages:
  - id: accept
    name: "accept"
    supervisor: true
    supervisor_prompt: скилл может сам все сделать - нужен autonomous режим.
    interactive: true
    agents: [planning]
    description: |
      засинкать codemanifest-ы с кодом.
    prompt: |
      сделать goga-accept чтобы манифесты flowmanager обновились т.к. много кода поменялось.
    skills:
      - goga-accept
    command: glm52

