name: accept-01
description: "accept"

prompt: |
  if goga binary not installed - install it with `pip install goga && goga connect claude`
  constraint: пиши все на русском. Не используй английский кроме спец терминов нужных.

stages:
  - id: accept
    name: "accept"
    supervisor: true
    supervisor_prompt: сделай автономным этот стейдж
    interactive: true
    agents: [planning]
    description: |
      засинкать codemanifest-ы с кодом.
    prompt: |
      сделать goga-accept чтобы манифесты flowmanager обновились т.к. много кода поменялось.
    skills:
      - goga-accept
    command: claude

  - id: commit
    name: "commit"
    supervisor: true
    supervisor_prompt: сделай автономным этот стейдж
    interactive: true
    agents: [planning]
    description: |
      привести в порядок и закоммитить все.
    prompt: |
      прогнать lint
      прогнать test
      починить их при ошибках
      обновить доку
      обновить release notes
      сделать коммит
    depends_on: [accept]
