// Code generated by tools/genstagestatus from pkg/state.AllStatuses(). DO NOT EDIT.
// Run 'make generate' after adding/removing a state.StageStatus const.

export const STAGE_STATUSES = [
  "pending",
  "planning",
  "awaiting_approval",
  "revising",
  "ready",
  "running",
  "retrying",
  "awaiting_user_input",
  "done",
  "failed",
  "hook_failed",
] as const

export type StageStatus = (typeof STAGE_STATUSES)[number]
