// Command genstagestatus generates
// pkg/web/dashboard/src/types/stage-status.generated.ts from
// state.AllStatuses(), the single Go source of truth for stage status names.
// Run via `make generate`; `make lint-ci` fails the build if the committed
// file is stale relative to pkg/state/state.go.
package main

import (
	"bytes"
	"fmt"
	"os"

	"github.com/akopichin/afm/pkg/state"
)

const outPath = "pkg/web/dashboard/src/types/stage-status.generated.ts"

const header = `// Code generated by tools/genstagestatus from pkg/state.AllStatuses(). DO NOT EDIT.
// Run 'make generate' after adding/removing a state.StageStatus const.
`

func main() {
	var buf bytes.Buffer
	buf.WriteString(header)
	buf.WriteString("\nexport const STAGE_STATUSES = [\n")
	for _, s := range state.AllStatuses() {
		fmt.Fprintf(&buf, "  %q,\n", string(s))
	}
	buf.WriteString("] as const\n\n")
	buf.WriteString("export type StageStatus = (typeof STAGE_STATUSES)[number]\n")

	if err := os.WriteFile(outPath, buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "genstagestatus: write %s: %v\n", outPath, err)
		os.Exit(1)
	}
}
